### ISSUE TITLE
Dicecord Offilne 2 days

### ISSUE THREAD

**Issue by Elexeia** [further-reading/Dicecord-Chatbot#2]
Been looking for status updates on when it will be back online.

**Comment by further-reading** [comment]
Thanks for the heads up, it's back now! The self-reconnect didn't trigger as it usually does. Gonna have a look into that when I get a chance and maybe add additional alerts to it.

**Comment by Elexeia** [comment]
Thanks a bunch. We'll keep an eye out, we love the bot and use it for MES
related CoDX 2.0 games.

--
Elexeia Rouse US2011027373

**Comment by Elexeia** [comment]
Looks like it went down again, not sure if this is an update but was alerted to it being offline again.

**Comment by further-reading** [comment]
Got it restarted again, sorry about that. For now I have a more generic error handler going until I have a chance to dig deeper into the problem.

**Comment by further-reading** [comment]
This was caused by connection issues with my ISP. It's sorted now and I have updated the reconnect code to handle it should it happen again.
