### ISSUE TITLE
Deprecate custom prefixes

### ISSUE THREAD

**Issue by further-reading** [further-reading/Dicecord-Chatbot#20]
Remove the custom prefix code (no longer possible following discord privacy updates)

**Comment by further-reading** [comment]
Fixed in https://github.com/further-reading/Dicecord-Chatbot/pull/22

**Comment by boredcity** [comment]
hi there, I love the bot, but really dislike that you have to add a whole mention before the roll...

is it possible to add a shorthand similar to [Dice Maiden](https://github.com/Humblemonk/DiceMaiden)'s `!roll`?  or is it conflicting with discord's privacy updates?

**Comment by further-reading** [comment]
Hey! So the issue is that I can't do both following the privacy updates - I had to choose between custom prefixes or the @-mention. One way to make the @-mention easier is to change the name of the bot in your server, so you could then use @dice for example.

**Comment by boredcity** [comment]
Oh, thanks for explaining and for the workaround! I'll try that.

**Comment by Gudini108** [comment]
for some reason Dicecord does not roll when you open a text chat in a voice chat. Is there a way to fix that or is it unfixable?)
![img](https://user-images.githubusercontent.com/99196810/184353277-b8313b2b-71b5-46bb-b354-e57fcfaa1234.jpg)

**Comment by further-reading** [comment]
That's not related to the custom prefix change. The voice chat text was not supported by the discord.py package last time I checked, but it seems they have version 2.0 out now which should support it but might break other code. I'll need some time to test.

**Comment by Gudini108** [comment]
Oh right. Sorry for asking in the wrong topic. Thanks anyway!
