### ISSUE TITLE
Add prefix option

### ISSUE THREAD

**Issue by further-reading** [further-reading/Dicecord-Chatbot#8]
Add command to set a prefix rather than use @mention.

**Comment by BeckTec** [comment]
I'de like to add command to allow successes on 7s for human players.

**Comment by further-reading** [comment]
Is that a mechanic? I don't recall anyone being able to change target numbers?

**Comment by BeckTec** [comment]
Humans have successes on 7 if they dont have a splat. Sorry new to github I think i put this in the wrong place

**Comment by further-reading** [comment]
Are you sure that's not some kind of house rule? I haven't played mortals in about a decade, but I checked my old copies of 1st ed nWoD and the God Machine rule updates and they both have success as 8+.

**Comment by BeckTec** [comment]
I was looking through my PDFs and your right. The Revised Storyteller System uses 7 but the nWOD on it is always 8. Sorry to bug you. And thanks for the dice roller its the best one out their for this game.
